version: '2.1'

services:
  coin-price:
    restart: on-failure
    image: coin-price
    build: .
    environment:
      NODE_ENV: production
    ports:
      - 3006:3006
    links:
      - mongo
  mongo:
    image: mongo
    ports: 
      - 27017:27017