version: '2.1'

services:
  coin-price:
    image: coin-price
    build: .
    environment:
      NODE_ENV: development
    ports:
      - 3006:3006
      - 9229:9229
    command: node --inspect=0.0.0.0:9229 app.js